### PR TITLE
Updates for mobile

### PR DESCRIPTION
**Pull request by Zsmith32**
Changing source branch from master. Closing existing PR: I had some issues with the template on Mobile #72

### CODE REVIEW

**Comment by lordmathis** [comment]
Hi @Zsmith32 , I finally got around to review your PR. Overall it looks good but I have two things:
* The font size in navbar looks huge so I would drop `font-size: 1.5em`  from body tag. Can you check if this change doesn't break any scailing issues that you were fixing.
* The footer is now kind off floating around if there's not enough content to push it down to the bottom of the page. This could probably be solved by encapsulating footer and main elements in a div with `flex-wrapper` class

**Comment by Zsmith32** [comment]
Hi @LordMathis,

Thanks for the feedback. Sorry it took so long to update lost a lot of free time with a job transition.

I updated the fontsize on navbar and fixed the footer to the bottom of the page.

**Comment by lordmathis** [comment]
Hi @Zsmith32 Thanks for the updates but I had something else in mind. I've pushed my updates to updates-for-mobile. Can you check if it works on Mobile? If you confirm I'll merge your PR and then I'll merge my changes on top of that.

**Comment by Zsmith32** [comment]
@LordMathis Your updates look great! Thanks!

**Pull request merged**
